/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Random;

public class Library {

    //roll Method #1
    public int[] roll(int n) {
        if (n <= 0 || n>6) {
            return new int[0];
        }

        int[] rolls = new int[n];
        Random random = new Random();

        for (int i = 0; i < n; i++) {
            rolls[i] = random.nextInt(6) + 1;
        }

        return rolls;
    }

    //isContainsDuplicates Method #2
    public boolean isContainsDuplicates(int[] array){
        ArrayList<Integer> elements = new ArrayList<>();

        for (int num : array) {
            if (elements.contains(num)) {
                return true;
            }
            elements.add(num);
        }

        return false;
    }

    //arrayAverage Method #3
    public double arrayAverage(int[] array) {
        if (array.length == 0) {
            return 0;
        }

        int sum = 0;
        for (int num : array) {
            sum += num;
        }

        return (double) sum / array.length;
    }
    //lowestArrayAverage Method #4
    public int[] lowestArrayAverage(int[][] arrays) {
        double lowestAverage=arrayAverage(arrays[0]);
        int[] lowestAvgArr=null;
        for(int[]element : arrays) {
            if(arrayAverage(element)<lowestAverage) {
                lowestAverage=arrayAverage(element);
                lowestAvgArr=element;
            }
        }
        return lowestAvgArr;
    }
}
